export const FETCH_ALL_TESTS = 'FETCH_ALL_TESTS';
export const FETCH_ALL_TESTS_COMPLETE = 'FETCH_ALL_TESTS_COMPLETE';
export const FETCH_ONE_TEST = 'FETCH_ONE_TEST';
export const FETCH_ONE_TEST_COMPLETE = 'FETCH_ONE_TEST_COMPLETE';
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION';
